#ifndef h88E0E9F1_F70F_4C14_BF63_D372947A75D2
#define h88E0E9F1_F70F_4C14_BF63_D372947A75D2

#define STDPLUS_INTROSPECTION_COMPILER_TARGET_LINUX 0
#define STDPLUS_INTROSPECTION_COMPILER_TARGET_OSX 1
#define STDPLUS_INTROSPECTION_COMPILER_TARGET_WINDOWS 2

#if defined( __GNUC__ )
#if defined( __linux__ )
#define STDPLUS_INTROSPECTION_COMPILER_TARGET STDPLUS_INTROSPECTION_COMPILER_TARGET_LINUX
#elif defined( __APPLE__ )
#define STDPLUS_INTROSPECTION_COMPILER_TARGET STDPLUS_INTROSPECTION_COMPILER_TARGET_OSX
#elif defined( __MINGW32__ )
#define STDPLUS_INTROSPECTION_COMPILER_TARGET STDPLUS_INTROSPECTION_COMPILER_TARGET_WINDOWS
#endif

#elif defined( _MSC_VER ) && defined( _WIN32 )
#define STDPLUS_INTROSPECTION_COMPILER_TARGET STDPLUS_INTROSPECTION_COMPILER_TARGET_WINDOWS
#endif

#endif
